package com.bharathvishal.biometricauthentication.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF7A564A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBD0)
val md_theme_light_onPrimaryContainer = Color(0xFF2E140C)
val md_theme_light_secondary = Color(0xFF695C58)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF1DFD9)
val md_theme_light_onSecondaryContainer = Color(0xFF231917)
val md_theme_light_tertiary = Color(0xFF645E4D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEBE2CC)
val md_theme_light_onTertiaryContainer = Color(0xFF1F1B0E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B1A)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B1A)
val md_theme_light_surfaceVariant = Color(0xFFEBE0DD)
val md_theme_light_onSurfaceVariant = Color(0xFF4C4544)
val md_theme_light_outline = Color(0xFF7D7573)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF33302F)
val md_theme_light_inverseOnSurface = Color(0xFFF7EFED)
val md_theme_light_inversePrimary = Color(0xFFEBBCAD)
val md_theme_light_surfaceTint = Color(0xFF7A564A)

val md_theme_dark_primary = Color(0xFFEBBCAD)
val md_theme_dark_onPrimary = Color(0xFF47291F)
val md_theme_dark_primaryContainer = Color(0xFF603F34)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBD0)
val md_theme_dark_secondary = Color(0xFFD4C3BE)
val md_theme_dark_onSecondary = Color(0xFF392E2B)
val md_theme_dark_secondaryContainer = Color(0xFF504441)
val md_theme_dark_onSecondaryContainer = Color(0xFFF1DFD9)
val md_theme_dark_tertiary = Color(0xFFCEC6B1)
val md_theme_dark_onTertiary = Color(0xFF353022)
val md_theme_dark_tertiaryContainer = Color(0xFF4C4637)
val md_theme_dark_onTertiaryContainer = Color(0xFFEBE2CC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1E1B1A)
val md_theme_dark_onBackground = Color(0xFFE8E1DF)
val md_theme_dark_surface = Color(0xFF1E1B1A)
val md_theme_dark_onSurface = Color(0xFFE8E1DF)
val md_theme_dark_surfaceVariant = Color(0xFF4C4544)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC4C2)
val md_theme_dark_outline = Color(0xFF978F8D)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE8E1DF)
val md_theme_dark_inverseOnSurface = Color(0xFF33302F)
val md_theme_dark_inversePrimary = Color(0xFF7A564A)
val md_theme_dark_surfaceTint = Color(0xFFEBBCAD)


val seed = Color(0xFFFECDBE)
